### PR TITLE
Fixes #10: Append UUID to each dependency jar filename

### LINKED ISSUE #10: Dependencies with same name and version, but different packages, are not embedded properly
> From @edenman, https://github.com/puniverse/capsule/issues/76

I have two dependencies with the same artifact id and same version number but different package names:

```
compile 'com.foo:annotations:MYVERSION'
compile 'com.foo.bar:annotations:MYVERSION'
```

I'm building my capsule using this Gradle task:

```
task fatCapsule(type: FatCapsule) {
  applicationClass 'com.foo.myapp.MyApp'
}
```

This is the stacktrace I get when I try to run the capsule:

```
2015-08-17_18:59:51.66690 java.io.IOException: Exception while extracting jar /data/pods/myapp/myapp/installs/myapp_8c5df4f148a811b604b0d23e41f5cccde6bfbe43/myapp.jar to app cache directory /data/app/myapp/.capsule/apps/com.foo.myapp.MyApp
2015-08-17_18:59:51.66706   at Capsule.extractCapsule0(Capsule.java:1641)
2015-08-17_18:59:51.66710   at Capsule.extractCapsule(Capsule.java:1633)
2015-08-17_18:59:51.66713   at Capsule.buildAppCacheDir0(Capsule.java:1567)
2015-08-17_18:59:51.66717   at Capsule.buildAppCacheDir(Capsule.java:1549)
2015-08-17_18:59:51.66720   at Capsule.getAppCache(Capsule.java:1498)
2015-08-17_18:59:51.66723   at Capsule.buildNativeLibraryPath(Capsule.java:1953)
2015-08-17_18:59:51.66723   at Capsule.buildSystemProperties(Capsule.java:1908)
2015-08-17_18:59:51.66726   at Capsule.buildSystemProperties(Capsule.java:1889)
2015-08-17_18:59:51.66729   at Capsule.buildJavaProcess(Capsule.java:1735)
2015-08-17_18:59:51.66732   at Capsule.buildProcess0(Capsule.java:1273)
2015-08-17_18:59:51.66736   at Capsule.buildProcess(Capsule.java:1264)
2015-08-17_18:59:51.66739   at Capsule.prelaunch0(Capsule.java:1237)
2015-08-17_18:59:51.66742   at Capsule.prelaunch(Capsule.java:1232)
2015-08-17_18:59:51.66745   at Capsule.prepareForLaunch(Capsule.java:1146)
2015-08-17_18:59:51.66746   at Capsule.launch(Capsule.java:1091)
2015-08-17_18:59:51.66749   at Capsule.main0(Capsule.java:332)
2015-08-17_18:59:51.66752   at Capsule.main(Capsule.java:311)
2015-08-17_18:59:51.66765 Caused by: java.nio.file.FileAlreadyExistsException: /data/app/myapp/.capsule/apps/com.foo.myapp.MyApp/annotations-MYVERSION.jar
2015-08-17_18:59:51.66769   at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
2015-08-17_18:59:51.66772   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
2015-08-17_18:59:51.66775   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
2015-08-17_18:59:51.66778   at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
2015-08-17_18:59:51.66784   at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
2015-08-17_18:59:51.66787   at java.nio.file.Files.newOutputStream(Files.java:216)
2015-08-17_18:59:51.66790   at java.nio.file.Files.copy(Files.java:3016)
2015-08-17_18:59:51.66793   at Capsule.writeFile(Capsule.java:3209)
2015-08-17_18:59:51.66798   at Capsule.extractJar(Capsule.java:2857)
2015-08-17_18:59:51.66801   at Capsule.extractCapsule0(Capsule.java:1639)
2015-08-17_18:59:51.66805   ... 16 more
```

### PR DESCRIPTION
**Pull request by edenman**
@danthegoodman

### CODE REVIEW

**Comment by edenman** [comment]
Happy to revise if you've got another idea of how to disambiguate dependencies with the same initial filename.

**Comment by pron** [comment]
I don't think this is a good approach. Maven coordinates are already universally-unique identifiers. By default, capsule translates dependencies to local jars based on the code in `dependencyToLocalJar` [here](https://github.com/puniverse/capsule/blob/master/capsule/src/main/java/Capsule.java#L3114) (tested [here](https://github.com/puniverse/capsule/blob/master/capsule/src/test/java/CapsuleTest.java#L1338))

**Comment by edenman** [comment]
@pron totally agreed, I just wasn't sure how to get the `group` information in the gradle task given an existing filename that doesn't include the group name, so I thought a UUID might be a quick workaround.

**Comment by pron** [comment]
Actually, the globally unique identifier should also include the (optional) classifier. However, it is extrmely unlikely that a capsule will contain more than one artifact of the same dependency. Capsule [should still support it](https://github.com/puniverse/capsule/issues/77), though.

**Comment by danthegoodman** [comment]
Hmm. I'm not a fan of appending UUIDs to everything, but you're right, I can't find a way to get additional info, like the group, given just the filename in the rename block.

So can you limit the rename to just the files from this configuration, and use just one rename statement? like so:

```
from(embedConfiguration) {
  rename { filename ->
    ...
  }
}
```

**Comment by edenman** [comment]
(We've moved to Shadow for unrelated reasons.  I'll close this PR out since nobody seems to be a fan of the uuids anyway.  Thanks for the help!)

**Pull request closed without merging**
